In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler


import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import acquire
import wrangle

In [2]:
df = acquire.get_telco_data()

In [3]:
df = wrangle.wrangle_telco()

In [4]:
df.head(70)

customer_id  gender  senior_citizen partner dependents  tenure  \
0   0002-ORFBO  Female               0     Yes        Yes       9   
1   0003-MKNFE    Male               0      No         No       9   
2   0004-TLHLJ    Male               0      No         No       4   
3   0011-IGKFF    Male               1     Yes         No      13   
4   0013-EXCHZ  Female               1     Yes         No       3   
..         ...     ...             ...     ...        ...     ...   
65  0111-KLBQG    Male               1     Yes        Yes      32   
66  0112-QAWRZ    Male               0     Yes        Yes      16   
67  0112-QWPNC    Male               0     Yes         No      49   
68  0114-IGABW  Female               0     Yes         No      71   
69  0114-PEGZZ  Female               0      No         No      33   

    monthly_charges  total_charges phone_service    multiple_lines  ...  \
0             65.60         593.30           Yes                No  ...   
1             59.90         542.40           Yes               Yes  ...   
2             73.90         280.85           Yes                No  ...   
3             98.00        1237.85           Yes                No  ...   
4             83.90         267.40           Yes                No  ...   
..              ...            ...           ...               ...  ...   
65            93.95        2861.45           Yes                No  ...   
66            90.80        1442.20           Yes               Yes  ...   
67            84.35        4059.35           Yes               Yes  ...   
68            58.25        4145.90            No  No phone service  ...   
69           107.55        3645.50           Yes               Yes  ...   

   streaming_tv streaming_movies paperless_billing contract_type_id  \
0           Yes               No               Yes                2   
1            No              Yes                No                1   
2            No               No               Yes                1   
3           Yes              Yes               Yes                1   
4           Yes               No               Yes                1   
..          ...              ...               ...              ...   
65          Yes              Yes               Yes                1   
66          Yes               No               Yes                1   
67          Yes              Yes                No                2   
68          Yes              Yes                No                3   
69          Yes              Yes                No                1   

   payment_type_id internet_service_type_id churn  automatic_payment  \
0                2                        1    No              False   
1                2                        1    No              False   
2                1                        2   Yes              False   
3                1                        2   Yes              False   
4                2                        2   Yes              False   
..             ...                      ...   ...                ...   
65               2                        2    No              False   
66               3                        2    No               True   
67               1                        1   Yes              False   
68               3                        1    No               True   
69               1                        2    No              False   

    monthly_charges_scaled  tenure_3_or_less  
0                 0.471144             False  
1                 0.414428             False  
2                 0.553731             False  
3                 0.793532             False  
4                 0.653234              True  
..                     ...               ...  
65                0.753234             False  
66                0.721891             False  
67                0.657711             False  
68                0.398010             False  
69                0.888557            

In [5]:
train, test = train_test_split(df, random_state=123, train_size=.80)

In [6]:
encoder = LabelEncoder()

encode_list = [
    'gender', 'partner', 'dependents', 'phone_service'
    , 'multiple_lines', 'online_security', 'online_backup'
    , 'device_protection', 'tech_support'
    , 'streaming_movies', 'streaming_tv', 'paperless_billing', 'churn'
    ]
               
               
               
for e in encode_list:
    train[e] = encoder.fit_transform(train[e])
    test[e] = encoder.transform(test[e])

# Optimize for recall

## Logit classifier without total_charges_scaled

In [7]:
# train, validate = train_test_split(train, random_state=123, test_size=.2)


# X_train = train[['senior_citizen', 'multiple_lines', 'streaming_tv', 'paperless_billing', 'contract_type_id', 'automatic_payment']]
# y_train = train[['churn']]
# X_val = validate[['senior_citizen', 'multiple_lines', 'streaming_tv', 'paperless_billing', 'contract_type_id', 'automatic_payment']]
# y_val = validate[['churn']]
# X_test = test[['senior_citizen', 'multiple_lines', 'streaming_tv', 'paperless_billing', 'contract_type_id', 'automatic_payment']]
# y_test = test[['churn']]

In [8]:
# logit = LogisticRegression(random_state = 123)
# logit.fit(X_train, y_train)

In [9]:
# y_pred = logit.predict(X_train)
# y_pred[:10]

In [10]:
# print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
#      .format(logit.score(X_train, y_train)))

In [11]:
# pd.DataFrame(confusion_matrix(y_train, y_pred))

In [12]:
# model_df = train[['churn']]
# model_df.rename(columns={'churn': 'actual'})

In [13]:
# model_df['logit_predictions'] = y_pred
# model_df.head()

In [14]:
# print(classification_report(y_train, y_pred))

## Logit classifier with tenure 3 or less

In [15]:
train, validate = train_test_split(train, random_state=123, test_size=.2)


X_train = train[['contract_type_id', 'senior_citizen',  'tenure_3_or_less', 'monthly_charges_scaled']]
y_train = train[['churn']]
X_val = validate[['contract_type_id', 'senior_citizen', 'tenure_3_or_less', 'monthly_charges_scaled']]
y_val = validate[['churn']]
X_test = test[['contract_type_id', 'senior_citizen',  'tenure_3_or_less', 'monthly_charges_scaled']]
y_test = test[['churn']]

In [16]:
logit = LogisticRegression(random_state = 123)
logit.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
y_pred = logit.predict(X_val)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [18]:
confusion_matrix(y_val, y_pred)

array([[756,  70],
       [170, 131]])

In [19]:
train.churn.value_counts()

0    3316
1    1191
Name: churn, dtype: int64

In [20]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_val, y_val)))

Accuracy of Logistic Regression classifier on training set: 0.79


In [21]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.92      0.86       826
           1       0.65      0.44      0.52       301

    accuracy                           0.79      1127
   macro avg       0.73      0.68      0.69      1127
weighted avg       0.77      0.79      0.77      1127



### Test Set

In [39]:
y_pred2 = logit.predict(X_test)
y_pred2[:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [40]:
confusion_matrix(y_test, y_pred2)

array([[927, 105],
       [216, 161]])

In [41]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_test, y_test)))

Accuracy of Logistic Regression classifier on training set: 0.77


In [42]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85      1032
           1       0.61      0.43      0.50       377

    accuracy                           0.77      1409
   macro avg       0.71      0.66      0.68      1409
weighted avg       0.76      0.77      0.76      1409



# Decision Tree with best features

In [22]:
clf = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=123)

In [23]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [24]:
y_pred = clf.predict(X_val)
y_pred[0:5]

array([0, 0, 0, 0, 0])

In [25]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_val, y_val)))

Accuracy of Decision Tree classifier on training set: 0.77


In [26]:
confusion_matrix(y_val, y_pred)

array([[813,  13],
       [241,  60]])

In [27]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.98      0.86       826
           1       0.82      0.20      0.32       301

    accuracy                           0.77      1127
   macro avg       0.80      0.59      0.59      1127
weighted avg       0.78      0.77      0.72      1127



### Test set

In [44]:
y_pred1 = clf.predict(X_test)
y_pred1[0:5]

array([0, 0, 0, 1, 0])

In [32]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.76


In [36]:
confusion_matrix(y_test, y_pred1)

array([[1011,   21],
       [ 313,   64]])

In [37]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.76      0.98      0.86      1032
           1       0.75      0.17      0.28       377

    accuracy                           0.76      1409
   macro avg       0.76      0.57      0.57      1409
weighted avg       0.76      0.76      0.70      1409

